services:
  fieldplay:
    build: .
    image: fieldplay:latest
    container_name: fieldplay
    restart: unless-stopped
    mem_limit: 128m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fieldplay.rule=Host(`fieldplay.mschwaerzler.com`)"
      - "traefik.http.routers.fieldplay.entrypoints=websecure"
      - "traefik.http.routers.fieldplay.tls=true"
      - "traefik.http.routers.fieldplay.tls.certresolver=le"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
